name: test

channels:
  - conda-forge
  - defaults

dependencies:

    # Core dependencies
  - python

    # ---- openff-toolkit deps ----
#  - openff-toolkit
  - numpy
  - smirnoff99frosst
  - openff-forcefields
  - openmm
  - networkx
  - mdtraj
  - xmltodict
  - ambertools
  - rdkit
    # ---- openff-toolkit deps ----

  - cmiles-base
  - pyyaml
  - networkx

    # Optional dependencies
  - rdkit
  - qcelemental

    # Testing
  - pytest
  - pytest-cov
  - codecov

  - pip:
      - git+git://github.com/openforcefield/openff-toolkit.git