name: test
channels:
  - openeye
  - conda-forge
  - defaults

dependencies:

    # Base Depends
  - python
  - openff-toolkit-base
  - openeye-toolkits
  - cmiles-base
  - pyyaml
  - networkx

    # Testing
  - pytest
  - pytest-cov
  - codecov
