name: test

channels:
  - conda-forge
  - defaults

dependencies:

    # Core dependencies
  - python

    # ---- openff-toolkit deps ----
#  - openff-toolkit-base
  - numpy
  - smirnoff99frosst
  - openff-forcefields
  - openmm
  - networkx
  - mdtraj
  - xmltodict
    # ---- openff-toolkit deps ----

  - numpy
  - pyyaml
  - networkx
  - jinja2
  - typing-extensions # py<3.8

    # Optional dependencies
  - rdkit
  - ambertools

    # Testing
  - pytest
  - pytest-cov
  - codecov

  - pip:
      - git+git://github.com/openforcefield/openff-toolkit.git