name: test

channels:
  - openeye
  - conda-forge
  - defaults

dependencies:

    # Core dependencies
  - python

    # ---- openff-toolkit deps ----
#  - openff-toolkit-base
  - numpy
  - smirnoff99frosst
  - openff-forcefields
  - openmm
  - networkx
  - mdtraj
  - xmltodict
    # ---- openff-toolkit deps ----

  - cmiles-base
  - pyyaml
  - networkx

    # Optional dependencies
  - openeye-toolkits=2019.10.2
  - rdkit

    # Testing
  - pytest
  - pytest-cov
  - codecov

  - pip:
      - git+git://github.com/openforcefield/openff-toolkit.git