name: test

channels:
  - conda-forge
  - defaults

dependencies:

    # Core dependencies
  - python

  - openff-toolkit-base >=0.9.2
  - numpy
  - pydantic
  - pyyaml
  - networkx
  - jinja2
  - typing-extensions # py<3.8

    # Optional dependencies
  - rdkit
  - ambertools

    # Testing
  - pytest
  - pytest-cov
  - codecov
