name: test

channels:
  - openeye
  - conda-forge
  - defaults

dependencies:

    # Core dependencies
  - python
  - openff-toolkit-base
  - cmiles-base
  - pyyaml
  - networkx

    # Optional dependencies
  - openeye-toolkits=2019.10.2

    # Testing
  - pytest
  - pytest-cov
  - codecov
