package:
  name: fragmenter
  version: "0.0.0"

source:
  path: ../..

build:
  number: 0

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - setuptools
    - openeye-toolkits>2020
    - rdkit
    - pyyaml

test:
  requires:
    - pytest
  imports:
    - fragmenter

about:
  home: https://github.com/openforcefield/fragmenter
  license: MIT License
  summary: A toolkit to fragment molecules for QM torsion scans and find torsions that need driving.
