name: CI

on:
  push:
    branches:
      - "master"
      - "maintenance/.+"
  pull_request:
    branches:
      - "master"
      - "maintenance/.+"
  schedule:
    # Nightly tests run on master by default:
    #   Scheduled workflows run on the latest commit on the default or base branch.
    #   (from https://help.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events-schedule)
    - cron: "0 0 * * *"

jobs:
  test:
    if: (github.event_name == 'schedule' && github.repository == 'openforcefield/fragmenter') || (github.event_name != 'schedule')
    name: Test on ${{ matrix.cfg.os }}, Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.cfg.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version:
          #- 3.6
          - 3.7
          # Uncomment when ready ;)
          # - 3.8
        cfg:
          - os: ubuntu-latest
          - os: macOS-latest


    env:
      CI_OS: ${{ matrix.cfg.os }}
      PYVER: ${{ matrix.python-version }}
      OE_LICENSE: ${{ github.workspace }}/oe_license.txt

    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ matrix.python-version }}
        activate-environment: test
        environment-file: devtools/conda-envs/meta.yaml
        auto-activate-base: false
    - name: Additional info about the build
      shell: bash
      run: |
        uname -a
        df -h
        ulimit -a
    - name: Decrypt OpenEye license
      shell: bash
      env:
        ENC_OE_LICENSE: ${{ secrets.OE_LICENSE }}
      run: |
        echo "${ENC_OE_LICENSE}" > ${OE_LICENSE}
    - name: Environment Information
      shell: bash -l {0}
      run: |
        conda info
        conda list
    - name: Check OpenEye license
      shell: bash -l {0}
      run: |
        python -c "import openeye; assert openeye.OEChemIsLicensed()"
    - name: Install package
      shell: bash -l {0}
      run: |
        python -m pip install --no-deps .
    - name: Test the package
      shell: bash -l {0}
      run: |
        pytest -v --cov=fragmenter --cov-report=xml --cov-config=setup.cfg fragmenter/tests
    - name: Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
        fail_ci_if_error: true